spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.179.130:3306/gulimall_pms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tPcx7szYsN4hK8fZpe4
      secret-key: M1i0IySb6zHpV6Ow8ZMnYeAnTx5zXn
      oss:
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: show_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
server:
  port: 12000
logging:
  level:
    com.atguigu.gulimall: debug
